# Username: postgres
# Database: postgres

services:
  postgresql:
    image: postgres:16.5
    container_name: postgresql
    network_mode: bridge
    restart: always
    environment:
      POSTGRES_PASSWORD: AdGeu7hS
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
