services:
  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'mohawkey'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'demo'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
volumes:
  data:
