# --------------------------------------------------------------------------------
# user: admin@admin.com
# pass: password
# --------------------------------------------------------------------------------

services:

  bookstack:
    image: linuxserver/bookstack:version-v26.05
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - APP_URL=https://wiki.home.io
      # docker run -it --rm --entrypoint /bin/bash lscr.io/linuxserver/bookstack:latest appkey
      - APP_KEY=base64:SkYLKdba38lfo5nfkp0yruqXx4s9Wb3nVSERqZbAS9o=

      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=${DATABASE}
      - DB_USERNAME=${USERNAME}
      - DB_PASSWORD=${PASSWORD}
    volumes:
      - data:/config
    ports:
      - 6875:80
    restart: unless-stopped


  mariadb:
    image: mariadb:12.3.2
    container_name: bookstack_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - db_data:/config

    restart: unless-stopped

volumes:
    data:
    db_data:
