services:

# ----------------------------------------------------------------------------------------------------
# update:
# adguard_home
# adguard_config
# ----------------------------------------------------------------------------------------------------

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - home:/opt/adguardhome/work
      - config:/opt/adguardhome/conf

# ----------------------------------------------------------------------------------------------------
# npm_data
# npm_letsencrypt
# ----------------------------------------------------------------------------------------------------

  nginx-proxy:
    container_name: nginx-proxy
    image: jc21/nginx-proxy-manager:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

# ----------------------------------------------------------------------------------------------------
# SECRET_ENCRYPTION_KEY: openssl rand -hex 32
# ----------------------------------------------------------------------------------------------------
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    network_mode: bridge
    restart: unless-stopped
    environment:
      - SECRET_ENCRYPTION_KEY= # 
    ports:
      - 7575:7575
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr_appdata:/appdata
      
# ----------------------------------------------------------------------------------------------------
# vaultwarden_data
# ----------------------------------------------------------------------------------------------------
      
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    network_mode: bridge
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.home.io"
      ADMIN_TOKEN: # ""
    ports:
      - 1080:80
    volumes:
      - vaultwarden:/data
      
# ----------------------------------------------------------------------------------------------------
#
# ----------------------------------------------------------------------------------------------------

volumes:
  data:
  letsencrypt:
  home:
  config:
  homarr_appdata:
  vaultwarden:
  
  
