# --------------------------------------------------------------------------------
# https://hub.docker.com/_/postgres
# --------------------------------------------------------------------------------

services:
  db:
    image: postgres:18.3
    container_name: postgresql
    restart: unless-stopped
    network_mode: bridge
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASS}'
      POSTGRES_DB: 'postgres'
      TZ: Europe/Brussels
    volumes:
      - data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  data:
