services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 3080:80/tcp
      - 3443:443/tcp
    volumes:
      - home:/opt/adguardhome/work
      - config:/opt/adguardhome/conf
volumes:
  home:
  config:
